Fix rvalue reference interface
The rvalue reference conditional was implemented with a
universal/forwarding reference.  This has problems:

Updated tests to do additional checks.  Added calls to set() with an
rvalue and (nonconst) lvalue version of 'cmp', which caused the following
link errors in the original picojson code:

undefined reference to `void picojson::value::set<bool>(bool&&)'
undefined reference to `void picojson::value::set<bool&>(bool&)'
undefined reference to `void picojson::value::set<bool>(bool&&)'
undefined reference to `void picojson::value::set<bool&>(bool&)'
undefined reference to `void picojson::value::set<double>(double&&)'
undefined reference to `void picojson::value::set<double&>(double&)'
undefined reference to `void picojson::value::set<double>(double&&)'
undefined reference to `void picojson::value::set<double&>(double&)'
undefined reference to `void picojson::value::set<std::string&>(std::string&)'

Afterwards all tests pass.

The problem is the definition of the template `set(T&&)` function,
which (due to being a forwarding reference) is a better match than the
set(T const&) versions when passing an rvalue or a non-const lvalue
(since it can be an exact match, while the T const& version must
undero a const-conversion).

The change in picojson is to remove the set(T&&) template and provide
the 3 explicit overloads for the rvalue-reference types intended
(where moving makes sense).  Now it stops matching the other types
that were not intended.